### ISSUE TITLE
diarization broken on latest whisperx replicate model

### ISSUE THREAD

**Issue by jecneps** [victor-upmeet/whisperx-replicate#1]
It doesn't seem like this is the actual repo that backs your replicate model [here](https://replicate.com/victor-upmeet/whisperx), but making an issue here was the only way I found to send you a message, apologies if this is an annoying place for it.

The latest version of your replicate model (5dfdddf6) doesn't diarize the output when the diarization flag is set. [Here](https://replicate.com/p/wegnqrlbjuifsjztwtw4mxcji4) is an example output. The second to last version (449341d3) does. [Here's](https://replicate.com/p/j6g3vpdb5fwwdkka7ukwjzks4u) the output for that. It's easy for me to use the older model, so I'm just letting you know about the bug in case you weren't aware of it yet. Cheers!

Also, thanks for making a useful whisperx replicate model!

**Comment by victor-upmeet** [comment]
This is in fact an old repo, I should sync the codebase with it and link it to the replicate model. Anyway, I will look into that asap and keep you posted!

This new version uses large-v3 (instead of large-v2 in previous version), and it brings some improvements about language detection (previous version only tries to detect language on the first 30s of the file, newest version tries multiple segments until a probability threshold is reached, or keeps the most probable language if the given threshold is never reached)

**Comment by victor-upmeet** [comment]
@jecneps The issue has been fixed in latest version 8f0fd34c, thanks for reporting it to me!

**Comment by victor-upmeet** [comment]
@jecneps The issue has been fixed in latest version 8f0fd34c, thanks for reporting it to me!
